services:
        postgres:
                container_name: hr-dashboard-db
                image: "postgres:16.3"
                env_file:
                        - ./compose.env
                environment:
                        - POSTGRES_DB=hr-dashboard
                ports:
                        - "5432:5432"
                networks:
                        node_net:
                                ipv4_address: 172.28.1.1
                volumes:
                        - ./postgres-volume:/var/lib/postgresql/data

        hr-dashboard-api:
                container_name: hr-dashboard-api
                image: "hr-dashboard-api:latest"
                build:
                        context: ./hr-dashboard-api
                        dockerfile: Dockerfile
                env_file:
                        - ./compose.env
                ports:
                        - "8080:8080"
                restart: on-failure:10
                networks:
                        node_net:
                                ipv4_address: 172.28.1.2
                depends_on:
                        - postgres

        hr-dashboard-ui:
                container_name: hr-dashboard-ui
                image: "hr-dashboard-ui:latest"
                build:
                        context: ./hr-dashboard-ui
                        dockerfile: Dockerfile
                ports:
                        - "4200:80"
                restart: always
                networks:
                        node_net:
                                ipv4_address: 172.28.1.3
                depends_on:
                        - hr-dashboard-api

networks:
        node_net:
                ipam:
                        config:
                                - subnet: 172.28.0.0/16
